/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ProfileRouteImport } from "./routes/profile"
import { Route as SplatRouteImport } from "./routes/$"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as UsersIndexRouteImport } from "./routes/users/index"
import { Route as RolesIndexRouteImport } from "./routes/roles/index"
import { Route as GroupsIndexRouteImport } from "./routes/groups/index"
import { Route as DatasourcesIndexRouteImport } from "./routes/datasources/index"
import { Route as ConnectorsIndexRouteImport } from "./routes/connectors/index"
import { Route as ApplicationsIndexRouteImport } from "./routes/applications/index"
import { Route as RolesCreateRouteImport } from "./routes/roles/create"
import { Route as ApplicationsCreateRouteImport } from "./routes/applications/create"
import { Route as RolesIdRouteRouteImport } from "./routes/roles/$id/route"
import { Route as ApplicationsIdRouteRouteImport } from "./routes/applications/$id/route"
import { Route as RolesIdIndexRouteImport } from "./routes/roles/$id/index"
import { Route as DatasourcesCreateIndexRouteImport } from "./routes/datasources/create/index"
import { Route as ConnectorsCreateIndexRouteImport } from "./routes/connectors/create/index"
import { Route as ApplicationsIdIndexRouteImport } from "./routes/applications/$id/index"
import { Route as UsersExternalIdRolesRouteImport } from "./routes/users/$externalId/roles"
import { Route as RolesIdDetailsRouteImport } from "./routes/roles/$id/details"
import { Route as GroupsExternalIdRolesRouteImport } from "./routes/groups/$externalId/roles"
import { Route as DatasourcesPicklistIdRouteImport } from "./routes/datasources/picklist.$id"
import { Route as DatasourcesFreetextIdRouteImport } from "./routes/datasources/freetext.$id"
import { Route as DatasourcesCreatePicklistRouteImport } from "./routes/datasources/create/picklist"
import { Route as DatasourcesCreateFreetextRouteImport } from "./routes/datasources/create/freetext"
import { Route as DatasourcesCreateCheckboxRouteImport } from "./routes/datasources/create/checkbox"
import { Route as DatasourcesCheckboxIdRouteImport } from "./routes/datasources/checkbox.$id"
import { Route as DatasourcesApipicklistIdRouteImport } from "./routes/datasources/apipicklist.$id"
import { Route as ConnectorsEntraIdRouteImport } from "./routes/connectors/entra.$id"
import { Route as ConnectorsCreateEntraRouteImport } from "./routes/connectors/create/entra"
import { Route as ApplicationsIdDetailsRouteImport } from "./routes/applications/$id/details"

const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: "/roles/",
  path: "/roles/",
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: "/groups/",
  path: "/groups/",
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIndexRoute = DatasourcesIndexRouteImport.update({
  id: "/datasources/",
  path: "/datasources/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: "/connectors/",
  path: "/connectors/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: "/applications/",
  path: "/applications/",
  getParentRoute: () => rootRouteImport,
} as any)
const RolesCreateRoute = RolesCreateRouteImport.update({
  id: "/roles/create",
  path: "/roles/create",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsCreateRoute = ApplicationsCreateRouteImport.update({
  id: "/applications/create",
  path: "/applications/create",
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdRouteRoute = RolesIdRouteRouteImport.update({
  id: "/roles/$id",
  path: "/roles/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRouteRoute = ApplicationsIdRouteRouteImport.update({
  id: "/applications/$id",
  path: "/applications/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdIndexRoute = RolesIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => RolesIdRouteRoute,
} as any)
const DatasourcesCreateIndexRoute = DatasourcesCreateIndexRouteImport.update({
  id: "/datasources/create/",
  path: "/datasources/create/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsCreateIndexRoute = ConnectorsCreateIndexRouteImport.update({
  id: "/connectors/create/",
  path: "/connectors/create/",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdIndexRoute = ApplicationsIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ApplicationsIdRouteRoute,
} as any)
const UsersExternalIdRolesRoute = UsersExternalIdRolesRouteImport.update({
  id: "/users/$externalId/roles",
  path: "/users/$externalId/roles",
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdDetailsRoute = RolesIdDetailsRouteImport.update({
  id: "/details",
  path: "/details",
  getParentRoute: () => RolesIdRouteRoute,
} as any)
const GroupsExternalIdRolesRoute = GroupsExternalIdRolesRouteImport.update({
  id: "/groups/$externalId/roles",
  path: "/groups/$externalId/roles",
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesPicklistIdRoute = DatasourcesPicklistIdRouteImport.update({
  id: "/datasources/picklist/$id",
  path: "/datasources/picklist/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesFreetextIdRoute = DatasourcesFreetextIdRouteImport.update({
  id: "/datasources/freetext/$id",
  path: "/datasources/freetext/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesCreatePicklistRoute =
  DatasourcesCreatePicklistRouteImport.update({
    id: "/datasources/create/picklist",
    path: "/datasources/create/picklist",
    getParentRoute: () => rootRouteImport,
  } as any)
const DatasourcesCreateFreetextRoute =
  DatasourcesCreateFreetextRouteImport.update({
    id: "/datasources/create/freetext",
    path: "/datasources/create/freetext",
    getParentRoute: () => rootRouteImport,
  } as any)
const DatasourcesCreateCheckboxRoute =
  DatasourcesCreateCheckboxRouteImport.update({
    id: "/datasources/create/checkbox",
    path: "/datasources/create/checkbox",
    getParentRoute: () => rootRouteImport,
  } as any)
const DatasourcesCheckboxIdRoute = DatasourcesCheckboxIdRouteImport.update({
  id: "/datasources/checkbox/$id",
  path: "/datasources/checkbox/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesApipicklistIdRoute =
  DatasourcesApipicklistIdRouteImport.update({
    id: "/datasources/apipicklist/$id",
    path: "/datasources/apipicklist/$id",
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectorsEntraIdRoute = ConnectorsEntraIdRouteImport.update({
  id: "/connectors/entra/$id",
  path: "/connectors/entra/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsCreateEntraRoute = ConnectorsCreateEntraRouteImport.update({
  id: "/connectors/create/entra",
  path: "/connectors/create/entra",
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdDetailsRoute = ApplicationsIdDetailsRouteImport.update({
  id: "/details",
  path: "/details",
  getParentRoute: () => ApplicationsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/profile": typeof ProfileRoute
  "/applications/$id": typeof ApplicationsIdRouteRouteWithChildren
  "/roles/$id": typeof RolesIdRouteRouteWithChildren
  "/applications/create": typeof ApplicationsCreateRoute
  "/roles/create": typeof RolesCreateRoute
  "/applications/": typeof ApplicationsIndexRoute
  "/connectors/": typeof ConnectorsIndexRoute
  "/datasources/": typeof DatasourcesIndexRoute
  "/groups/": typeof GroupsIndexRoute
  "/roles/": typeof RolesIndexRoute
  "/users/": typeof UsersIndexRoute
  "/applications/$id/details": typeof ApplicationsIdDetailsRoute
  "/connectors/create/entra": typeof ConnectorsCreateEntraRoute
  "/connectors/entra/$id": typeof ConnectorsEntraIdRoute
  "/datasources/apipicklist/$id": typeof DatasourcesApipicklistIdRoute
  "/datasources/checkbox/$id": typeof DatasourcesCheckboxIdRoute
  "/datasources/create/checkbox": typeof DatasourcesCreateCheckboxRoute
  "/datasources/create/freetext": typeof DatasourcesCreateFreetextRoute
  "/datasources/create/picklist": typeof DatasourcesCreatePicklistRoute
  "/datasources/freetext/$id": typeof DatasourcesFreetextIdRoute
  "/datasources/picklist/$id": typeof DatasourcesPicklistIdRoute
  "/groups/$externalId/roles": typeof GroupsExternalIdRolesRoute
  "/roles/$id/details": typeof RolesIdDetailsRoute
  "/users/$externalId/roles": typeof UsersExternalIdRolesRoute
  "/applications/$id/": typeof ApplicationsIdIndexRoute
  "/connectors/create/": typeof ConnectorsCreateIndexRoute
  "/datasources/create/": typeof DatasourcesCreateIndexRoute
  "/roles/$id/": typeof RolesIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/profile": typeof ProfileRoute
  "/applications/create": typeof ApplicationsCreateRoute
  "/roles/create": typeof RolesCreateRoute
  "/applications": typeof ApplicationsIndexRoute
  "/connectors": typeof ConnectorsIndexRoute
  "/datasources": typeof DatasourcesIndexRoute
  "/groups": typeof GroupsIndexRoute
  "/roles": typeof RolesIndexRoute
  "/users": typeof UsersIndexRoute
  "/applications/$id/details": typeof ApplicationsIdDetailsRoute
  "/connectors/create/entra": typeof ConnectorsCreateEntraRoute
  "/connectors/entra/$id": typeof ConnectorsEntraIdRoute
  "/datasources/apipicklist/$id": typeof DatasourcesApipicklistIdRoute
  "/datasources/checkbox/$id": typeof DatasourcesCheckboxIdRoute
  "/datasources/create/checkbox": typeof DatasourcesCreateCheckboxRoute
  "/datasources/create/freetext": typeof DatasourcesCreateFreetextRoute
  "/datasources/create/picklist": typeof DatasourcesCreatePicklistRoute
  "/datasources/freetext/$id": typeof DatasourcesFreetextIdRoute
  "/datasources/picklist/$id": typeof DatasourcesPicklistIdRoute
  "/groups/$externalId/roles": typeof GroupsExternalIdRolesRoute
  "/roles/$id/details": typeof RolesIdDetailsRoute
  "/users/$externalId/roles": typeof UsersExternalIdRolesRoute
  "/applications/$id": typeof ApplicationsIdIndexRoute
  "/connectors/create": typeof ConnectorsCreateIndexRoute
  "/datasources/create": typeof DatasourcesCreateIndexRoute
  "/roles/$id": typeof RolesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$": typeof SplatRoute
  "/profile": typeof ProfileRoute
  "/applications/$id": typeof ApplicationsIdRouteRouteWithChildren
  "/roles/$id": typeof RolesIdRouteRouteWithChildren
  "/applications/create": typeof ApplicationsCreateRoute
  "/roles/create": typeof RolesCreateRoute
  "/applications/": typeof ApplicationsIndexRoute
  "/connectors/": typeof ConnectorsIndexRoute
  "/datasources/": typeof DatasourcesIndexRoute
  "/groups/": typeof GroupsIndexRoute
  "/roles/": typeof RolesIndexRoute
  "/users/": typeof UsersIndexRoute
  "/applications/$id/details": typeof ApplicationsIdDetailsRoute
  "/connectors/create/entra": typeof ConnectorsCreateEntraRoute
  "/connectors/entra/$id": typeof ConnectorsEntraIdRoute
  "/datasources/apipicklist/$id": typeof DatasourcesApipicklistIdRoute
  "/datasources/checkbox/$id": typeof DatasourcesCheckboxIdRoute
  "/datasources/create/checkbox": typeof DatasourcesCreateCheckboxRoute
  "/datasources/create/freetext": typeof DatasourcesCreateFreetextRoute
  "/datasources/create/picklist": typeof DatasourcesCreatePicklistRoute
  "/datasources/freetext/$id": typeof DatasourcesFreetextIdRoute
  "/datasources/picklist/$id": typeof DatasourcesPicklistIdRoute
  "/groups/$externalId/roles": typeof GroupsExternalIdRolesRoute
  "/roles/$id/details": typeof RolesIdDetailsRoute
  "/users/$externalId/roles": typeof UsersExternalIdRolesRoute
  "/applications/$id/": typeof ApplicationsIdIndexRoute
  "/connectors/create/": typeof ConnectorsCreateIndexRoute
  "/datasources/create/": typeof DatasourcesCreateIndexRoute
  "/roles/$id/": typeof RolesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$"
    | "/profile"
    | "/applications/$id"
    | "/roles/$id"
    | "/applications/create"
    | "/roles/create"
    | "/applications/"
    | "/connectors/"
    | "/datasources/"
    | "/groups/"
    | "/roles/"
    | "/users/"
    | "/applications/$id/details"
    | "/connectors/create/entra"
    | "/connectors/entra/$id"
    | "/datasources/apipicklist/$id"
    | "/datasources/checkbox/$id"
    | "/datasources/create/checkbox"
    | "/datasources/create/freetext"
    | "/datasources/create/picklist"
    | "/datasources/freetext/$id"
    | "/datasources/picklist/$id"
    | "/groups/$externalId/roles"
    | "/roles/$id/details"
    | "/users/$externalId/roles"
    | "/applications/$id/"
    | "/connectors/create/"
    | "/datasources/create/"
    | "/roles/$id/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/$"
    | "/profile"
    | "/applications/create"
    | "/roles/create"
    | "/applications"
    | "/connectors"
    | "/datasources"
    | "/groups"
    | "/roles"
    | "/users"
    | "/applications/$id/details"
    | "/connectors/create/entra"
    | "/connectors/entra/$id"
    | "/datasources/apipicklist/$id"
    | "/datasources/checkbox/$id"
    | "/datasources/create/checkbox"
    | "/datasources/create/freetext"
    | "/datasources/create/picklist"
    | "/datasources/freetext/$id"
    | "/datasources/picklist/$id"
    | "/groups/$externalId/roles"
    | "/roles/$id/details"
    | "/users/$externalId/roles"
    | "/applications/$id"
    | "/connectors/create"
    | "/datasources/create"
    | "/roles/$id"
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/profile"
    | "/applications/$id"
    | "/roles/$id"
    | "/applications/create"
    | "/roles/create"
    | "/applications/"
    | "/connectors/"
    | "/datasources/"
    | "/groups/"
    | "/roles/"
    | "/users/"
    | "/applications/$id/details"
    | "/connectors/create/entra"
    | "/connectors/entra/$id"
    | "/datasources/apipicklist/$id"
    | "/datasources/checkbox/$id"
    | "/datasources/create/checkbox"
    | "/datasources/create/freetext"
    | "/datasources/create/picklist"
    | "/datasources/freetext/$id"
    | "/datasources/picklist/$id"
    | "/groups/$externalId/roles"
    | "/roles/$id/details"
    | "/users/$externalId/roles"
    | "/applications/$id/"
    | "/connectors/create/"
    | "/datasources/create/"
    | "/roles/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ProfileRoute: typeof ProfileRoute
  ApplicationsIdRouteRoute: typeof ApplicationsIdRouteRouteWithChildren
  RolesIdRouteRoute: typeof RolesIdRouteRouteWithChildren
  ApplicationsCreateRoute: typeof ApplicationsCreateRoute
  RolesCreateRoute: typeof RolesCreateRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  DatasourcesIndexRoute: typeof DatasourcesIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ConnectorsCreateEntraRoute: typeof ConnectorsCreateEntraRoute
  ConnectorsEntraIdRoute: typeof ConnectorsEntraIdRoute
  DatasourcesApipicklistIdRoute: typeof DatasourcesApipicklistIdRoute
  DatasourcesCheckboxIdRoute: typeof DatasourcesCheckboxIdRoute
  DatasourcesCreateCheckboxRoute: typeof DatasourcesCreateCheckboxRoute
  DatasourcesCreateFreetextRoute: typeof DatasourcesCreateFreetextRoute
  DatasourcesCreatePicklistRoute: typeof DatasourcesCreatePicklistRoute
  DatasourcesFreetextIdRoute: typeof DatasourcesFreetextIdRoute
  DatasourcesPicklistIdRoute: typeof DatasourcesPicklistIdRoute
  GroupsExternalIdRolesRoute: typeof GroupsExternalIdRolesRoute
  UsersExternalIdRolesRoute: typeof UsersExternalIdRolesRoute
  ConnectorsCreateIndexRoute: typeof ConnectorsCreateIndexRoute
  DatasourcesCreateIndexRoute: typeof DatasourcesCreateIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/profile": {
      id: "/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$": {
      id: "/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/users/": {
      id: "/users/"
      path: "/users"
      fullPath: "/users/"
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/roles/": {
      id: "/roles/"
      path: "/roles"
      fullPath: "/roles/"
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/groups/": {
      id: "/groups/"
      path: "/groups"
      fullPath: "/groups/"
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/": {
      id: "/datasources/"
      path: "/datasources"
      fullPath: "/datasources/"
      preLoaderRoute: typeof DatasourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/connectors/": {
      id: "/connectors/"
      path: "/connectors"
      fullPath: "/connectors/"
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/": {
      id: "/applications/"
      path: "/applications"
      fullPath: "/applications/"
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/roles/create": {
      id: "/roles/create"
      path: "/roles/create"
      fullPath: "/roles/create"
      preLoaderRoute: typeof RolesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/create": {
      id: "/applications/create"
      path: "/applications/create"
      fullPath: "/applications/create"
      preLoaderRoute: typeof ApplicationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/roles/$id": {
      id: "/roles/$id"
      path: "/roles/$id"
      fullPath: "/roles/$id"
      preLoaderRoute: typeof RolesIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/$id": {
      id: "/applications/$id"
      path: "/applications/$id"
      fullPath: "/applications/$id"
      preLoaderRoute: typeof ApplicationsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/roles/$id/": {
      id: "/roles/$id/"
      path: "/"
      fullPath: "/roles/$id/"
      preLoaderRoute: typeof RolesIdIndexRouteImport
      parentRoute: typeof RolesIdRouteRoute
    }
    "/datasources/create/": {
      id: "/datasources/create/"
      path: "/datasources/create"
      fullPath: "/datasources/create/"
      preLoaderRoute: typeof DatasourcesCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/connectors/create/": {
      id: "/connectors/create/"
      path: "/connectors/create"
      fullPath: "/connectors/create/"
      preLoaderRoute: typeof ConnectorsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/$id/": {
      id: "/applications/$id/"
      path: "/"
      fullPath: "/applications/$id/"
      preLoaderRoute: typeof ApplicationsIdIndexRouteImport
      parentRoute: typeof ApplicationsIdRouteRoute
    }
    "/users/$externalId/roles": {
      id: "/users/$externalId/roles"
      path: "/users/$externalId/roles"
      fullPath: "/users/$externalId/roles"
      preLoaderRoute: typeof UsersExternalIdRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/roles/$id/details": {
      id: "/roles/$id/details"
      path: "/details"
      fullPath: "/roles/$id/details"
      preLoaderRoute: typeof RolesIdDetailsRouteImport
      parentRoute: typeof RolesIdRouteRoute
    }
    "/groups/$externalId/roles": {
      id: "/groups/$externalId/roles"
      path: "/groups/$externalId/roles"
      fullPath: "/groups/$externalId/roles"
      preLoaderRoute: typeof GroupsExternalIdRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/picklist/$id": {
      id: "/datasources/picklist/$id"
      path: "/datasources/picklist/$id"
      fullPath: "/datasources/picklist/$id"
      preLoaderRoute: typeof DatasourcesPicklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/freetext/$id": {
      id: "/datasources/freetext/$id"
      path: "/datasources/freetext/$id"
      fullPath: "/datasources/freetext/$id"
      preLoaderRoute: typeof DatasourcesFreetextIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/create/picklist": {
      id: "/datasources/create/picklist"
      path: "/datasources/create/picklist"
      fullPath: "/datasources/create/picklist"
      preLoaderRoute: typeof DatasourcesCreatePicklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/create/freetext": {
      id: "/datasources/create/freetext"
      path: "/datasources/create/freetext"
      fullPath: "/datasources/create/freetext"
      preLoaderRoute: typeof DatasourcesCreateFreetextRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/create/checkbox": {
      id: "/datasources/create/checkbox"
      path: "/datasources/create/checkbox"
      fullPath: "/datasources/create/checkbox"
      preLoaderRoute: typeof DatasourcesCreateCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/checkbox/$id": {
      id: "/datasources/checkbox/$id"
      path: "/datasources/checkbox/$id"
      fullPath: "/datasources/checkbox/$id"
      preLoaderRoute: typeof DatasourcesCheckboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/datasources/apipicklist/$id": {
      id: "/datasources/apipicklist/$id"
      path: "/datasources/apipicklist/$id"
      fullPath: "/datasources/apipicklist/$id"
      preLoaderRoute: typeof DatasourcesApipicklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/connectors/entra/$id": {
      id: "/connectors/entra/$id"
      path: "/connectors/entra/$id"
      fullPath: "/connectors/entra/$id"
      preLoaderRoute: typeof ConnectorsEntraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/connectors/create/entra": {
      id: "/connectors/create/entra"
      path: "/connectors/create/entra"
      fullPath: "/connectors/create/entra"
      preLoaderRoute: typeof ConnectorsCreateEntraRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/applications/$id/details": {
      id: "/applications/$id/details"
      path: "/details"
      fullPath: "/applications/$id/details"
      preLoaderRoute: typeof ApplicationsIdDetailsRouteImport
      parentRoute: typeof ApplicationsIdRouteRoute
    }
  }
}

interface ApplicationsIdRouteRouteChildren {
  ApplicationsIdDetailsRoute: typeof ApplicationsIdDetailsRoute
  ApplicationsIdIndexRoute: typeof ApplicationsIdIndexRoute
}

const ApplicationsIdRouteRouteChildren: ApplicationsIdRouteRouteChildren = {
  ApplicationsIdDetailsRoute: ApplicationsIdDetailsRoute,
  ApplicationsIdIndexRoute: ApplicationsIdIndexRoute,
}

const ApplicationsIdRouteRouteWithChildren =
  ApplicationsIdRouteRoute._addFileChildren(ApplicationsIdRouteRouteChildren)

interface RolesIdRouteRouteChildren {
  RolesIdDetailsRoute: typeof RolesIdDetailsRoute
  RolesIdIndexRoute: typeof RolesIdIndexRoute
}

const RolesIdRouteRouteChildren: RolesIdRouteRouteChildren = {
  RolesIdDetailsRoute: RolesIdDetailsRoute,
  RolesIdIndexRoute: RolesIdIndexRoute,
}

const RolesIdRouteRouteWithChildren = RolesIdRouteRoute._addFileChildren(
  RolesIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ProfileRoute: ProfileRoute,
  ApplicationsIdRouteRoute: ApplicationsIdRouteRouteWithChildren,
  RolesIdRouteRoute: RolesIdRouteRouteWithChildren,
  ApplicationsCreateRoute: ApplicationsCreateRoute,
  RolesCreateRoute: RolesCreateRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  DatasourcesIndexRoute: DatasourcesIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ConnectorsCreateEntraRoute: ConnectorsCreateEntraRoute,
  ConnectorsEntraIdRoute: ConnectorsEntraIdRoute,
  DatasourcesApipicklistIdRoute: DatasourcesApipicklistIdRoute,
  DatasourcesCheckboxIdRoute: DatasourcesCheckboxIdRoute,
  DatasourcesCreateCheckboxRoute: DatasourcesCreateCheckboxRoute,
  DatasourcesCreateFreetextRoute: DatasourcesCreateFreetextRoute,
  DatasourcesCreatePicklistRoute: DatasourcesCreatePicklistRoute,
  DatasourcesFreetextIdRoute: DatasourcesFreetextIdRoute,
  DatasourcesPicklistIdRoute: DatasourcesPicklistIdRoute,
  GroupsExternalIdRolesRoute: GroupsExternalIdRolesRoute,
  UsersExternalIdRolesRoute: UsersExternalIdRolesRoute,
  ConnectorsCreateIndexRoute: ConnectorsCreateIndexRoute,
  DatasourcesCreateIndexRoute: DatasourcesCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
