// This file is auto-generated by @hey-api/openapi-ts

export const ApplicationSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        description: {
            type: 'string',
            nullable: true
        },
        logoUrl: {
            type: 'string',
            nullable: true
        },
        permissions: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Permission'
            }
        },
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const CreateApplicationSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        logoUrl: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const CreatePermissionSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const CreateRoleSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const PermissionSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        description: {
            type: 'string',
            nullable: true
        },
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const ProblemDetailsSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            nullable: true
        },
        title: {
            type: 'string',
            nullable: true
        },
        status: {
            type: 'integer',
            format: 'int32',
            nullable: true
        },
        detail: {
            type: 'string',
            nullable: true
        },
        instance: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const RoleSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        logoUrl: {
            type: 'string',
            nullable: true
        },
        permissions: {
            type: 'array',
            items: {
                required: ['id', 'name'],
                type: 'object',
                properties: {
                    id: {
                        type: 'integer',
                        format: 'int32'
                    },
                    name: {
                        type: 'string'
                    }
                }
            }
        }
    }
} as const;

export const SimpleApplicationSchema = {
    required: ['name'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string'
        },
        permissions: {
            type: 'array',
            items: {
                required: ['name'],
                type: 'object',
                properties: {
                    id: {
                        type: 'integer',
                        format: 'int32'
                    },
                    name: {
                        type: 'string'
                    }
                }
            }
        }
    }
} as const;