// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetAllApplicationsData, GetAllApplicationsResponse, CreateApplicationData, CreateApplicationResponse, DeleteApplicationData, DeleteApplicationResponse, DeleteApplicationError, GetApplicationData, GetApplicationResponse, GetApplicationError, UpdateApplicationData, UpdateApplicationResponse, UpdateApplicationError, GetPermissionListData, GetPermissionListResponse, DeletePermissionData, DeletePermissionResponse, DeletePermissionError, GetPermissionData, GetPermissionResponse, GetPermissionError, UpdatePermissionData, UpdatePermissionResponse, UpdatePermissionError, CreatePermissionData, CreatePermissionResponse, GetAllConnectorsData, GetAllConnectorsResponse, GetAvailableConnectorTypesData, GetAvailableConnectorTypesResponse, DeleteConnectorData, DeleteConnectorResponse, DeleteConnectorError, GetEntraConnectorData, GetEntraConnectorResponse, GetEntraConnectorError, UpdateEntraConnectorData, UpdateEntraConnectorResponse, UpdateEntraConnectorError, CreateEntraConnectorData, CreateEntraConnectorResponse, GetAllRolesData, GetAllRolesResponse, GetAllRolesError, CreateRoleData, CreateRoleResponse, DeleteRoleData, DeleteRoleResponse, DeleteRoleError, GetRoleData, GetRoleResponse, GetRoleError, UpdateRoleData, UpdateRoleResponse, UpdateRoleError, RemoveRoleData, RemoveRoleResponse, RemoveRoleError, AddPermissionData, AddPermissionError, GetUserData, GetUserResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getAllApplications = <ThrowOnError extends boolean = false>(options?: Options<GetAllApplicationsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllApplicationsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications',
        ...options
    });
};

export const createApplication = <ThrowOnError extends boolean = false>(options: Options<CreateApplicationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateApplicationResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteApplication = <ThrowOnError extends boolean = false>(options: Options<DeleteApplicationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteApplicationResponse, DeleteApplicationError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/{id}',
        ...options
    });
};

export const getApplication = <ThrowOnError extends boolean = false>(options: Options<GetApplicationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApplicationResponse, GetApplicationError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/{id}',
        ...options
    });
};

export const updateApplication = <ThrowOnError extends boolean = false>(options: Options<UpdateApplicationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateApplicationResponse, UpdateApplicationError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getPermissionList = <ThrowOnError extends boolean = false>(options?: Options<GetPermissionListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetPermissionListResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/permissions',
        ...options
    });
};

export const deletePermission = <ThrowOnError extends boolean = false>(options: Options<DeletePermissionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeletePermissionResponse, DeletePermissionError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/{applicationId}/permissions/{id}',
        ...options
    });
};

export const getPermission = <ThrowOnError extends boolean = false>(options: Options<GetPermissionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPermissionResponse, GetPermissionError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/{applicationId}/permissions/{id}',
        ...options
    });
};

export const updatePermission = <ThrowOnError extends boolean = false>(options: Options<UpdatePermissionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdatePermissionResponse, UpdatePermissionError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/{applicationId}/permissions/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const createPermission = <ThrowOnError extends boolean = false>(options: Options<CreatePermissionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreatePermissionResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/applications/{applicationId}/permissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getAllConnectors = <ThrowOnError extends boolean = false>(options?: Options<GetAllConnectorsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllConnectorsResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/connectors',
        ...options
    });
};

export const getAvailableConnectorTypes = <ThrowOnError extends boolean = false>(options?: Options<GetAvailableConnectorTypesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAvailableConnectorTypesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/connectors/available',
        ...options
    });
};

export const deleteConnector = <ThrowOnError extends boolean = false>(options: Options<DeleteConnectorData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteConnectorResponse, DeleteConnectorError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/connectors/{id}',
        ...options
    });
};

export const getEntraConnector = <ThrowOnError extends boolean = false>(options: Options<GetEntraConnectorData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetEntraConnectorResponse, GetEntraConnectorError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/connectors/entra/{id}',
        ...options
    });
};

export const updateEntraConnector = <ThrowOnError extends boolean = false>(options: Options<UpdateEntraConnectorData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateEntraConnectorResponse, UpdateEntraConnectorError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/connectors/entra/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const createEntraConnector = <ThrowOnError extends boolean = false>(options: Options<CreateEntraConnectorData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateEntraConnectorResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/connectors/entra',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getAllRoles = <ThrowOnError extends boolean = false>(options?: Options<GetAllRolesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllRolesResponse, GetAllRolesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/roles',
        ...options
    });
};

export const createRole = <ThrowOnError extends boolean = false>(options: Options<CreateRoleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateRoleResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/roles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteRole = <ThrowOnError extends boolean = false>(options: Options<DeleteRoleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteRoleResponse, DeleteRoleError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/roles/{id}',
        ...options
    });
};

export const getRole = <ThrowOnError extends boolean = false>(options: Options<GetRoleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetRoleResponse, GetRoleError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/roles/{id}',
        ...options
    });
};

export const updateRole = <ThrowOnError extends boolean = false>(options: Options<UpdateRoleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateRoleResponse, UpdateRoleError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/roles/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const removeRole = <ThrowOnError extends boolean = false>(options: Options<RemoveRoleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveRoleResponse, RemoveRoleError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/roles/{roleId}/permissions/{permissionId}',
        ...options
    });
};

export const addPermission = <ThrowOnError extends boolean = false>(options: Options<AddPermissionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<unknown, AddPermissionError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/roles/{roleId}/permissions/{permissionId}',
        ...options
    });
};

export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUserResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/users/me',
        ...options
    });
};