// This file is auto-generated by @hey-api/openapi-ts

export type Application = {
    id?: number;
    name: string;
    description?: (string) | null;
    logoUrl?: (string) | null;
    permissions?: Array<Permission>;
};

export type CreateApplication = {
    name: string;
    description?: (string) | null;
    logoUrl?: (string) | null;
};

export type CreatePermission = {
    name: string;
    description?: (string) | null;
};

export type Permission = {
    id: number;
    name: string;
    description?: (string) | null;
};

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
};

export type GetAllApplicationsResponse = (Array<Application>);

export type GetAllApplicationsError = unknown;

export type CreateApplicationData = {
    body: CreateApplication;
};

export type CreateApplicationResponse = (Application);

export type CreateApplicationError = unknown;

export type GetApplicationData = {
    path: {
        id: number;
    };
};

export type GetApplicationResponse = (Application);

export type GetApplicationError = (ProblemDetails);

export type UpdateApplicationData = {
    body: CreateApplication;
    path: {
        id: number;
    };
};

export type UpdateApplicationResponse = (Application);

export type UpdateApplicationError = (ProblemDetails);

export type DeleteApplicationData = {
    path: {
        id: number;
    };
};

export type DeleteApplicationResponse = (void);

export type DeleteApplicationError = (ProblemDetails);

export type GetPermissionData = {
    path: {
        applicationId: number;
        id: number;
    };
};

export type GetPermissionResponse = (Permission);

export type GetPermissionError = (ProblemDetails);

export type UpdatePermissionData = {
    body: CreatePermission;
    path: {
        applicationId: number;
        id: number;
    };
};

export type UpdatePermissionResponse = (Permission);

export type UpdatePermissionError = (ProblemDetails);

export type DeletePermissionData = {
    path: {
        applicationId: number;
        id: number;
    };
};

export type DeletePermissionResponse = (void);

export type DeletePermissionError = (ProblemDetails);

export type CreatePermissionData = {
    body: CreatePermission;
    path: {
        applicationId: number;
    };
};

export type CreatePermissionResponse = (Permission);

export type CreatePermissionError = unknown;