CREATE TABLE [dbo].[Role] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Name] NVARCHAR(255) NOT NULL,
    [Description] NVARCHAR(255) NULL,
    [Created] DATETIME2 NOT NULL CONSTRAINT DF_Role_Created DEFAULT SYSUTCDATETIME(),
    [Modified] DATETIME2 NOT NULL CONSTRAINT DF_Role_Modified DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Role PRIMARY KEY (Id)
);