CREATE TABLE [dbo].[Secret] (
    [Key] NVARCHAR(200) NOT NULL,
    [Value] NVARCHAR(MAX) NOT NULL,
    [Created] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [Modified] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_Secret] PRIMARY KEY ([Key])
);
