// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5006/' | (string & {});
};

export type ApiAuthType = 'None' | 'ApiKey' | 'OAuthClientCredentials';

export type ApiListConfig = {
    endpoint: string;
    authType: ApiAuthType;
    tokenEndpoint?: null | string;
    clientId?: null | string;
    scope?: null | string;
    apiKeyHeader?: null | string;
    keyPath?: null | string;
    displayValuePath?: null | string;
    cacheMinutes?: number;
};

export type ApiListDataSource = {
    id: number;
    name: string;
    description?: null | string;
    key: string;
    config?: null | ApiListConfig;
};

export type Application = {
    id: number;
    logoUrl?: null | string;
    permissions?: Array<Permission>;
    description?: null | string;
    name: string;
};

export type AzureOAuthOptions = {
    tenantId?: string;
    authority?: null | string;
    domain: string;
    audience: string;
    clientId: string;
    validateAudience?: boolean;
};

export type ConnectorGroup = {
    id: string;
    name: string;
    description?: null | string;
};

export type ConnectorType = 'Entra' | 'Auth0';

export type ConnectorTypeEntry = {
    id?: number;
    name: string;
    logoUrl?: null | string;
};

export type ConnectorUser = {
    id: string;
    email: string;
    displayName: string;
    firstName?: null | string;
    lastName?: null | string;
};

export type CreateApiListDataSource = {
    name: string;
    description?: null | string;
    key: string;
    config: ApiListConfig;
    clientSecret?: null | string;
    apiKey?: null | string;
};

export type CreateApplication = {
    logoUrl?: null | string;
    description?: null | string;
    name: string;
};

export type CreateDataSourceValue = {
    key: string;
    displayValue: string;
    sortOrder?: number;
};

export type CreateEntraConnector = {
    name: string;
    config: null | EntraConfig;
    clientId: string;
    clientSecret: string;
    audience?: null | string;
};

export type CreateFreeTextDataSource = {
    name: string;
    description?: null | string;
    key: string;
};

export type CreatePermission = {
    description?: null | string;
    name: string;
};

export type CreateRole = {
    description?: null | string;
    name: string;
};

export type CreateStaticListDataSource = {
    name: string;
    description?: null | string;
    key: string;
    values?: Array<CreateDataSourceValue>;
};

export type DataSourceType = 'FreeText' | 'StaticList' | 'ApiList';

export type DataSourceTypeEntry = {
    id?: number;
    name: string;
};

export type DataSourceValue = {
    id: number;
    key: string;
    displayValue: string;
    sortOrder?: number;
};

export type EntraConfig = {
    tenantId: string;
};

export type EntraConnector = {
    id: number;
    config: null | EntraConfig;
    slug: string;
    clientId: string;
    audience?: null | string;
    name: string;
};

export type FreeTextDataSource = {
    id: number;
    name: string;
    description?: null | string;
    key: string;
};

export type PagedResultOfConnectorGroup = {
    results: Array<ConnectorGroup>;
    total: number;
};

export type PagedResultOfConnectorUser = {
    results: Array<ConnectorUser>;
    total: number;
};

export type Permission = {
    id: number;
    name: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type Role = {
    description?: null | string;
    permissions?: Array<Permission>;
    id: number;
    name: string;
};

export type SimpleApplication = {
    id: number;
    name: string;
    permissions?: Array<SimplePermission>;
};

export type SimpleConnector = {
    id: number;
    name: string;
    type: ConnectorType;
    clientId: string;
};

export type SimpleDataSource = {
    id: number;
    name: string;
    key: string;
    type: DataSourceType;
};

export type SimplePermission = {
    id: number;
    name: string;
};

export type StaticListDataSource = {
    id: number;
    name: string;
    description?: null | string;
    key: string;
    values?: Array<DataSourceValue>;
};

export type User = {
    id: unknown;
    emailAddress: string;
    firstName: string;
    lastName: string;
};

export type GetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetConfigurationResponses = {
    /**
     * OK
     */
    200: AzureOAuthOptions;
};

export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];

export type GetAllApplicationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/applications';
};

export type GetAllApplicationsResponses = {
    /**
     * OK
     */
    200: Array<Application>;
};

export type GetAllApplicationsResponse = GetAllApplicationsResponses[keyof GetAllApplicationsResponses];

export type CreateApplicationData = {
    body: CreateApplication;
    path?: never;
    query?: never;
    url: '/api/applications';
};

export type CreateApplicationResponses = {
    /**
     * Created
     */
    201: Application;
};

export type CreateApplicationResponse = CreateApplicationResponses[keyof CreateApplicationResponses];

export type DeleteApplicationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/applications/{id}';
};

export type DeleteApplicationErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApplicationError = DeleteApplicationErrors[keyof DeleteApplicationErrors];

export type DeleteApplicationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApplicationResponse = DeleteApplicationResponses[keyof DeleteApplicationResponses];

export type GetApplicationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/applications/{id}';
};

export type GetApplicationErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApplicationError = GetApplicationErrors[keyof GetApplicationErrors];

export type GetApplicationResponses = {
    /**
     * OK
     */
    200: Application;
};

export type GetApplicationResponse = GetApplicationResponses[keyof GetApplicationResponses];

export type UpdateApplicationData = {
    body: CreateApplication;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/applications/{id}';
};

export type UpdateApplicationErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateApplicationError = UpdateApplicationErrors[keyof UpdateApplicationErrors];

export type UpdateApplicationResponses = {
    /**
     * OK
     */
    200: Application;
};

export type UpdateApplicationResponse = UpdateApplicationResponses[keyof UpdateApplicationResponses];

export type GetPermissionListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/applications/permissions';
};

export type GetPermissionListResponses = {
    /**
     * OK
     */
    200: Array<SimpleApplication>;
};

export type GetPermissionListResponse = GetPermissionListResponses[keyof GetPermissionListResponses];

export type DeletePermissionData = {
    body?: never;
    path: {
        applicationId: number;
        id: number;
    };
    query?: never;
    url: '/api/applications/{applicationId}/permissions/{id}';
};

export type DeletePermissionErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeletePermissionError = DeletePermissionErrors[keyof DeletePermissionErrors];

export type DeletePermissionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePermissionResponse = DeletePermissionResponses[keyof DeletePermissionResponses];

export type GetPermissionData = {
    body?: never;
    path: {
        applicationId: number;
        id: number;
    };
    query?: never;
    url: '/api/applications/{applicationId}/permissions/{id}';
};

export type GetPermissionErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetPermissionError = GetPermissionErrors[keyof GetPermissionErrors];

export type GetPermissionResponses = {
    /**
     * OK
     */
    200: Permission;
};

export type GetPermissionResponse = GetPermissionResponses[keyof GetPermissionResponses];

export type UpdatePermissionData = {
    body: CreatePermission;
    path: {
        applicationId: number;
        id: number;
    };
    query?: never;
    url: '/api/applications/{applicationId}/permissions/{id}';
};

export type UpdatePermissionErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdatePermissionError = UpdatePermissionErrors[keyof UpdatePermissionErrors];

export type UpdatePermissionResponses = {
    /**
     * OK
     */
    200: Permission;
};

export type UpdatePermissionResponse = UpdatePermissionResponses[keyof UpdatePermissionResponses];

export type CreatePermissionData = {
    body: CreatePermission;
    path: {
        applicationId: number;
    };
    query?: never;
    url: '/api/applications/{applicationId}/permissions';
};

export type CreatePermissionResponses = {
    /**
     * Created
     */
    201: Permission;
};

export type CreatePermissionResponse = CreatePermissionResponses[keyof CreatePermissionResponses];

export type GetAllConnectorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/connectors';
};

export type GetAllConnectorsResponses = {
    /**
     * OK
     */
    200: Array<SimpleConnector>;
};

export type GetAllConnectorsResponse = GetAllConnectorsResponses[keyof GetAllConnectorsResponses];

export type GetAvailableConnectorTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/connectors/available';
};

export type GetAvailableConnectorTypesResponses = {
    /**
     * OK
     */
    200: Array<ConnectorTypeEntry>;
};

export type GetAvailableConnectorTypesResponse = GetAvailableConnectorTypesResponses[keyof GetAvailableConnectorTypesResponses];

export type DeleteConnectorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/connectors/{id}';
};

export type DeleteConnectorErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectorError = DeleteConnectorErrors[keyof DeleteConnectorErrors];

export type DeleteConnectorResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteConnectorResponse = DeleteConnectorResponses[keyof DeleteConnectorResponses];

export type GetEntraConnectorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/connectors/entra/{id}';
};

export type GetEntraConnectorErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetEntraConnectorError = GetEntraConnectorErrors[keyof GetEntraConnectorErrors];

export type GetEntraConnectorResponses = {
    /**
     * OK
     */
    200: EntraConnector;
};

export type GetEntraConnectorResponse = GetEntraConnectorResponses[keyof GetEntraConnectorResponses];

export type UpdateEntraConnectorData = {
    body: CreateEntraConnector;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/connectors/entra/{id}';
};

export type UpdateEntraConnectorErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateEntraConnectorError = UpdateEntraConnectorErrors[keyof UpdateEntraConnectorErrors];

export type UpdateEntraConnectorResponses = {
    /**
     * OK
     */
    200: EntraConnector;
};

export type UpdateEntraConnectorResponse = UpdateEntraConnectorResponses[keyof UpdateEntraConnectorResponses];

export type CreateEntraConnectorData = {
    body: CreateEntraConnector;
    path?: never;
    query?: never;
    url: '/api/connectors/entra';
};

export type CreateEntraConnectorResponses = {
    /**
     * Created
     */
    201: EntraConnector;
};

export type CreateEntraConnectorResponse = CreateEntraConnectorResponses[keyof CreateEntraConnectorResponses];

export type GetAllDataSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/datasources';
};

export type GetAllDataSourcesResponses = {
    /**
     * OK
     */
    200: Array<SimpleDataSource>;
};

export type GetAllDataSourcesResponse = GetAllDataSourcesResponses[keyof GetAllDataSourcesResponses];

export type GetDataSourceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/datasources/types';
};

export type GetDataSourceTypesResponses = {
    /**
     * OK
     */
    200: Array<DataSourceTypeEntry>;
};

export type GetDataSourceTypesResponse = GetDataSourceTypesResponses[keyof GetDataSourceTypesResponses];

export type DeleteDataSourceData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/datasources/{id}';
};

export type DeleteDataSourceErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteDataSourceError = DeleteDataSourceErrors[keyof DeleteDataSourceErrors];

export type DeleteDataSourceResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteDataSourceResponse = DeleteDataSourceResponses[keyof DeleteDataSourceResponses];

export type GetFreetextDataSourceData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/datasources/freetext/{id}';
};

export type GetFreetextDataSourceErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetFreetextDataSourceError = GetFreetextDataSourceErrors[keyof GetFreetextDataSourceErrors];

export type GetFreetextDataSourceResponses = {
    /**
     * OK
     */
    200: FreeTextDataSource;
};

export type GetFreetextDataSourceResponse = GetFreetextDataSourceResponses[keyof GetFreetextDataSourceResponses];

export type UpdateFreetextDataSourceData = {
    body: CreateFreeTextDataSource;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/datasources/freetext/{id}';
};

export type UpdateFreetextDataSourceErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateFreetextDataSourceError = UpdateFreetextDataSourceErrors[keyof UpdateFreetextDataSourceErrors];

export type UpdateFreetextDataSourceResponses = {
    /**
     * OK
     */
    200: FreeTextDataSource;
};

export type UpdateFreetextDataSourceResponse = UpdateFreetextDataSourceResponses[keyof UpdateFreetextDataSourceResponses];

export type CreateFreetextDataSourceData = {
    body: CreateFreeTextDataSource;
    path?: never;
    query?: never;
    url: '/api/datasources/freetext';
};

export type CreateFreetextDataSourceResponses = {
    /**
     * Created
     */
    201: FreeTextDataSource;
};

export type CreateFreetextDataSourceResponse = CreateFreetextDataSourceResponses[keyof CreateFreetextDataSourceResponses];

export type GetStaticlistDataSourceData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/datasources/staticlist/{id}';
};

export type GetStaticlistDataSourceErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetStaticlistDataSourceError = GetStaticlistDataSourceErrors[keyof GetStaticlistDataSourceErrors];

export type GetStaticlistDataSourceResponses = {
    /**
     * OK
     */
    200: StaticListDataSource;
};

export type GetStaticlistDataSourceResponse = GetStaticlistDataSourceResponses[keyof GetStaticlistDataSourceResponses];

export type UpdateStaticlistDataSourceData = {
    body: CreateStaticListDataSource;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/datasources/staticlist/{id}';
};

export type UpdateStaticlistDataSourceErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateStaticlistDataSourceError = UpdateStaticlistDataSourceErrors[keyof UpdateStaticlistDataSourceErrors];

export type UpdateStaticlistDataSourceResponses = {
    /**
     * OK
     */
    200: StaticListDataSource;
};

export type UpdateStaticlistDataSourceResponse = UpdateStaticlistDataSourceResponses[keyof UpdateStaticlistDataSourceResponses];

export type CreateStaticlistDataSourceData = {
    body: CreateStaticListDataSource;
    path?: never;
    query?: never;
    url: '/api/datasources/staticlist';
};

export type CreateStaticlistDataSourceResponses = {
    /**
     * Created
     */
    201: StaticListDataSource;
};

export type CreateStaticlistDataSourceResponse = CreateStaticlistDataSourceResponses[keyof CreateStaticlistDataSourceResponses];

export type GetApilistDataSourceData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/datasources/apilist/{id}';
};

export type GetApilistDataSourceErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApilistDataSourceError = GetApilistDataSourceErrors[keyof GetApilistDataSourceErrors];

export type GetApilistDataSourceResponses = {
    /**
     * OK
     */
    200: ApiListDataSource;
};

export type GetApilistDataSourceResponse = GetApilistDataSourceResponses[keyof GetApilistDataSourceResponses];

export type UpdateApilistDataSourceData = {
    body: CreateApiListDataSource;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/datasources/apilist/{id}';
};

export type UpdateApilistDataSourceErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateApilistDataSourceError = UpdateApilistDataSourceErrors[keyof UpdateApilistDataSourceErrors];

export type UpdateApilistDataSourceResponses = {
    /**
     * OK
     */
    200: ApiListDataSource;
};

export type UpdateApilistDataSourceResponse = UpdateApilistDataSourceResponses[keyof UpdateApilistDataSourceResponses];

export type CreateApilistDataSourceData = {
    body: CreateApiListDataSource;
    path?: never;
    query?: never;
    url: '/api/datasources/apilist';
};

export type CreateApilistDataSourceResponses = {
    /**
     * Created
     */
    201: ApiListDataSource;
};

export type CreateApilistDataSourceResponse = CreateApilistDataSourceResponses[keyof CreateApilistDataSourceResponses];

export type GetDataSourceValuesData = {
    body?: never;
    path: {
        dataSourceId: number;
    };
    query?: never;
    url: '/api/datasources/{dataSourceId}/values';
};

export type GetDataSourceValuesErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetDataSourceValuesError = GetDataSourceValuesErrors[keyof GetDataSourceValuesErrors];

export type GetDataSourceValuesResponses = {
    /**
     * OK
     */
    200: Array<DataSourceValue>;
};

export type GetDataSourceValuesResponse = GetDataSourceValuesResponses[keyof GetDataSourceValuesResponses];

export type AddDataSourceValueData = {
    body: CreateDataSourceValue;
    path: {
        dataSourceId: number;
    };
    query?: never;
    url: '/api/datasources/{dataSourceId}/values';
};

export type AddDataSourceValueErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type AddDataSourceValueError = AddDataSourceValueErrors[keyof AddDataSourceValueErrors];

export type AddDataSourceValueResponses = {
    /**
     * Created
     */
    201: DataSourceValue;
};

export type AddDataSourceValueResponse = AddDataSourceValueResponses[keyof AddDataSourceValueResponses];

export type RemoveDataSourceValueData = {
    body?: never;
    path: {
        dataSourceId: number;
        valueId: number;
    };
    query?: never;
    url: '/api/datasources/{dataSourceId}/values/{valueId}';
};

export type RemoveDataSourceValueErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type RemoveDataSourceValueError = RemoveDataSourceValueErrors[keyof RemoveDataSourceValueErrors];

export type RemoveDataSourceValueResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveDataSourceValueResponse = RemoveDataSourceValueResponses[keyof RemoveDataSourceValueResponses];

export type UpdateDataSourceValueData = {
    body: CreateDataSourceValue;
    path: {
        dataSourceId: number;
        valueId: number;
    };
    query?: never;
    url: '/api/datasources/{dataSourceId}/values/{valueId}';
};

export type UpdateDataSourceValueErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateDataSourceValueError = UpdateDataSourceValueErrors[keyof UpdateDataSourceValueErrors];

export type UpdateDataSourceValueResponses = {
    /**
     * OK
     */
    200: DataSourceValue;
};

export type UpdateDataSourceValueResponse = UpdateDataSourceValueResponses[keyof UpdateDataSourceValueResponses];

export type GetGroupsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number;
        PageSize?: number;
        Search?: string;
    };
    url: '/api/groups';
};

export type GetGroupsResponses = {
    /**
     * OK
     */
    200: PagedResultOfConnectorGroup;
};

export type GetGroupsResponse = GetGroupsResponses[keyof GetGroupsResponses];

export type GetAllRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type GetAllRolesErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type GetAllRolesError = GetAllRolesErrors[keyof GetAllRolesErrors];

export type GetAllRolesResponses = {
    /**
     * OK
     */
    200: Array<Role>;
};

export type GetAllRolesResponse = GetAllRolesResponses[keyof GetAllRolesResponses];

export type CreateRoleData = {
    body: CreateRole;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type CreateRoleResponses = {
    /**
     * Created
     */
    201: Role;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type DeleteRoleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type DeleteRoleErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors];

export type DeleteRoleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type GetRoleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type GetRoleErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetRoleError = GetRoleErrors[keyof GetRoleErrors];

export type GetRoleResponses = {
    /**
     * OK
     */
    200: Role;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type UpdateRoleData = {
    body: CreateRole;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type UpdateRoleErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * OK
     */
    200: Role;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type RemoveRoleData = {
    body?: never;
    path: {
        roleId: number;
        permissionId: number;
    };
    query?: never;
    url: '/api/roles/{roleId}/permissions/{permissionId}';
};

export type RemoveRoleErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type RemoveRoleError = RemoveRoleErrors[keyof RemoveRoleErrors];

export type RemoveRoleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveRoleResponse = RemoveRoleResponses[keyof RemoveRoleResponses];

export type AddPermissionData = {
    body?: never;
    path: {
        roleId: number;
        permissionId: number;
    };
    query?: never;
    url: '/api/roles/{roleId}/permissions/{permissionId}';
};

export type AddPermissionErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type AddPermissionError = AddPermissionErrors[keyof AddPermissionErrors];

export type AddPermissionResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number;
        PageSize?: number;
        Search?: string;
    };
    url: '/api/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: PagedResultOfConnectorUser;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];
